[build]
  # If your source is on the `docs` branch, you can still leave this out—
  # Netlify picks up the branch you set in the UI.
  # command = "npm run build"      # (if you build)

  publish = "docs"                 # <-- your folder